SalonSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('salon/', include('salon.urls')),
]

salon/urls.py
from django.urls import path
from .views import IndexView, CourseListView, ReservationView, MonthWithScheduleCalendar
from . import views

app_name = 'salon'

urlpatterns = [
    path('', IndexView.as_view(), name='top'),
    path('list/', CourseListView.as_view(), name='course'),
    path('reservation/', ReservationView.as_view(), name='reservation'),
    path('reservation/<int:id>', ReservationView.as_view(), name='reservation'),
    path('success/', views.success, name='success'),
    path('', MonthWithScheduleCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', MonthWithScheduleCalendar.as_view(), name='month'),
]

salon/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

class CourseMaster(models.Model):
    course_name = models.CharField(max_length=255, blank=False)
    description = models.CharField(max_length=255, blank=False)
    genre = models.CharField(max_length=255, blank=False)
    icon = models.BinaryField(blank=True, null=True)
    
    def __str__(self):
        return self.course_name

    class Meta:
        db_table = 'course_master'

class Reserver(models.Model):
    reserver_name = models.CharField(max_length=255, blank=False)
    email = models.EmailField(max_length=255, blank=False)
    tel = PhoneNumberField()
    reservation_date = models.DateTimeField(blank=False)
    course = models.ForeignKey(CourseMaster, to_field='id', on_delete=models.PROTECT)
    
    def __str__(self):
        return str(self.reservation_date)

    class Meta:
        db_table = 'reserver'

salon/forms.py
# forms.py
from django import forms
from .models import CourseMaster, Reserver

class ReserverForm(forms.ModelForm):
    class Meta:
        model = Reserver
        fields = ['reserver_name', 'email', 'tel', 'reservation_date']
    course_id = forms.ModelChoiceField(queryset=CourseMaster.objects.all(), to_field_name='id',label="course_name")
    
    def clean_course_id(self):
        course_name = self.cleaned_data['course_id']
        try:
            # 入力されたコース名に対応するCourseMasterを取得
            course_master = CourseMaster.objects.get(course_name=course_name)
            return course_master.id
        except CourseMaster.DoesNotExist:
            # 存在しない場合は適切に処理
            raise forms.ValidationError(f"Course '{course_name}' does not exist.")

salon/views.py
import datetime
from django.shortcuts import render
from .models import CourseMaster, Reserver
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView
from .forms import ReserverForm
from django.contrib.messages.views import SuccessMessageMixin
from .mixins import MonthWithScheduleMixin

def success(request, **kwargs):
    return render(request, 'index.html')

class IndexView(TemplateView):
    template_name = 'index.html'

class CourseListView(ListView):
    template_name = 'list.html'
    model = CourseMaster

class ReservationView(SuccessMessageMixin, CreateView):
    template_name = 'reservation.html'
    form_class = ReserverForm
    model = Reserver
    success_url = reverse_lazy('salon:success')
    success_message = '予約完了しました。'
    def form_valid(self, form):
        # commit=Falseで一時保存
        reserver_instance = form.save(commit=False)
        # ここでcourse_idを設定
        reserver_instance.course_id = form.cleaned_data['course_id']
        # 最終的な保存
        reserver_instance.save()
        return super().form_valid(form)

class MonthWithScheduleCalendar(MonthWithScheduleMixin, TemplateView):
    """スケジュール付きの月間カレンダーを表示するビュー"""
    template_name = 'month.html'
    model = Reserver
    date_field = 'reservation_date'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        # ReserverモデルとCourseMasterモデルのデータを取得
        reservers_with_courses = Reserver.objects.select_related('course').all()
        combined_data = []
        for reserver in reservers_with_courses:
            combined_item = {
                'id': reserver.course.id,
                'course_name': reserver.course.course_name,
            }
            combined_data.append(combined_item)
        context.update({
            'calendar_context': calendar_context,
            'combined_data': combined_data
        })
        return context

salon/templates/footer.html
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'footer.css' %}">
</head>
<footer>
    <small>Copyright&copy; <a href="index.html">SalonSite</a> All Rights Reserved.</small>
</footer>

salon/templates/header.html
{% now "Y" as current_year %}
{% now "m" as current_month %}
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'header.css' %}">
</head>
<header>
    <aside id="mainimg"><img src="{% static 'images/mainimg.jpg' %}"></aside>
</header>
<nav id="menubar">
    <ul>
    <li><a href="{% url 'salon:top' %}">トップ</a></li>
    <li><a href="{% url 'salon:course' %}">コース一覧</a></li>
    <li><a href="{% url 'salon:reservation' %}">コース予約</a></li>
    <li><a href="{% url 'salon:month' year=current_year month=current_month %}">予約状況</a></li>
    </ul>
</nav>

salon/templates/index.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>トップページ</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" href="{% static 'index.css' %}">
    </head>

    <body>
        {% if messages %}
            <div class="messages" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
        <div id="container">
            {% include 'header.html' %}
            <div id="contents">
                <div class="box">
                    <div class="text">
                        <h3>コンテンツタイトルが入るよ</h3>
                        <p>コンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよ</p>
                        <p>コンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよ</p>
                        <p>コンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよ</p>
                    </div>
                    <div class="pict"><img src="{% static 'images/mock1.png' %}"></div>
                </div>
                <div class="box">
                    <div class="text">
                        <h3>コンテンツタイトルが入るよ</h3>
                        <p>コンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよ</p>
                        <p>コンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよ</p>
                        <p>コンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよ</p>
                    </div>
                    <div class="pict"><img src="{% static 'images/mock1.png' %}"></div>
                </div>
                <div class="box">
                    <div class="text">
                        <h3>コンテンツタイトルが入るよ</h3>
                        <p>コンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよ</p>
                        <p>コンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよ</p>
                        <p>コンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよコンテンツの文章が入るよ</p>
                    </div>
                    <div class="pict"><img src="{% static 'images/mock1.png' %}"></div>
                </div>
            </div>
            {% include 'footer.html' %}
        </div>
    </body>
</html>

salon/templates/list.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>コース一覧</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" href="{% static 'list.css' %}">
    </head>

    <body>
        <div id="container">
            {% include 'header.html' %}
            <div id="contents">
                {% for course in object_list %}
                <div class="box">
                    <div class="pict"><img src="{% static 'images/mock1.png' %}"></div>
                    <div class="text">
                        <h3>{{ course.course_name }}</h3>
                        <p>{{ course.description }}</p>
                    </div>
                    <div class="btn">
                        <button onclick="location.href='{% url 'salon:reservation' id=course.id %}'" type="button" class="btn-layout">予約</button>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% include 'footer.html' %}
        </div>
    </body>
</html>

salon/templates/month.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>予約状況</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" href="{% static 'month.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    </head>

    <body>
        <div id="container">
          {% include 'header.html' %}
            <div id="contents">
                <table class="table">
                    <thead>
                        <tr>
                            {% for w in calendar_context.week_names %}
                                <th>{{ w }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                    {% for week_day_schedles in calendar_context.month_day_schedules %}
                        <tr>
                            {% for day, schedules in week_day_schedles.items %}
                                {% if now == day %}
                                    <td class="table-success">
                                        {% else %}
                                    <td>
                                {% endif %}
                            <div>
                                {% if calendar_context.month_current.month != day.month %}
                                    {{ day | date:"m/d" }}
                                {% else %}
                                    {{ day.day }}
                                {% endif %}
                                {% for schedule in schedules %}
                                    {% for data in combined_data %}
                                        {% if schedule.course.id == data.id %}
                                            <p style="font-size: 14px;">{{ schedule.reservation_date | date:"H:i" }} {{ data.course_name }}</p>
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
                            </div>
                            </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% include 'footer.html' %}
        </div>
    </body>
</html>

salon/templates/reservation.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>コース予約</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" href="{% static 'reservation.css' %}">
    </head>

    <body>
      {% if messages %}
        <div class="messages" role="alert">
          {% for message in messages %}
            {{ message }}
          {% endfor %}
        </div>
      {% endif %}
        <div id="container">
          {% include 'header.html' %}
            <div id="contents">
              <div class="input-form">
                <form action="{% url 'salon:reservation' %}" method="POST">
                  {% csrf_token %}
                  <table class="form-table">
                    <tr>
                      <th>予約者名</th>
                      <td>{{ form.reserver_name }}</td>
                    </tr>
                    <tr>
                      <th>メールアドレス</th>
                      <td>{{ form.email }}</td>
                    </tr>
                    <tr>
                      <th>電話番号</th>
                      <td>{{ form.tel }}</td>
                    </tr>
                    <tr>
                      <th>予約日時</th>
                      <td>{{ form.reservation_date }}</td>
                    </tr>
                    <tr>
                      <th>コース</th>
                      <td>{{ form.course_id }}</td>
                    </tr>
                  </table>
                  <br />
                  <button class="btn btn-layout" type="submit">予約確定</button>
                </form>
              </div>
            </div>
            {% include 'footer.html' %}
        </div>
    </body>
</html>